---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by iTexZ.
--- DateTime: 05/11/2020 02:17
---

local TextPanels = {
    Background = { Dictionary = "OnestlaFilsDePuteGrr", Texture = "gradient_bgd", Y = 38, Width = 431, Height = 42 },
}

---@type Panel
function OnlylifeUI.RenderSprite2(Dictionary, Texture)
    local CurrentMenu = OnlylifeUI.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, CurrentMenu.Y + TextPanels.Background.Y + CurrentMenu.SubtitleHeight + OnlylifeUI.ItemOffset + (OnlylifeUI.StatisticPanelCount * 42), TextPanels.Background.Width + CurrentMenu.WidthOffset, TextPanels.Background.Height + 200, 0, 255, 255, 255, 255);
            OnlylifeUI.StatisticPanelCount = OnlylifeUI.StatisticPanelCount + 1
        end
    end
end

function OnlylifeUI.RenderSprite(Dictionary,Texture)
    local CurrentMenu = OnlylifeUI.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then

            RenderSprite(Dictionary, Texture, CurrentMenu.X, CurrentMenu.Y + CurrentMenu.SubtitleHeight + OnlylifeUI.ItemOffset, 431 + (CurrentMenu.WidthOffset / 1), 228)
            

            OnlylifeUI.ItemOffset = OnlylifeUI.ItemOffset + 228
        end
    end
end

local TextPanelVehicle = {
    Background = { Dictionary = "OnestlaFilsDePuteGrr", Texture = "gradient_bgd", Y = 0.25, Width = 431, Height = 42 },
}

---@type Panel
function OnlylifeUI.RenderWeapon(Dictionary, Texture)
    local CurrentMenu = OnlylifeUI.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, 625.25, TextPanelVehicle.Background.Width + CurrentMenu.WidthOffset, TextPanelVehicle.Background.Height + 200, 0, 255, 255, 255, 255);
            OnlylifeUI.StatisticPanelCount = OnlylifeUI.StatisticPanelCount + 1
        end
    end
end

---@type Panel
function OnlylifeUI.RenderVehicle(Dictionary, Texture)
    local CurrentMenu = OnlylifeUI.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, 560.25, TextPanelVehicle.Background.Width + CurrentMenu.WidthOffset, TextPanelVehicle.Background.Height + 200, 0, 255, 255, 255, 255);
            OnlylifeUI.StatisticPanelCount = OnlylifeUI.StatisticPanelCount + 1
        end
    end
end

---@type Panel
function OnlylifeUI.RenderCaisse(Dictionary, Texture)
    local CurrentMenu = OnlylifeUI.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, 258, TextPanelVehicle.Background.Width + CurrentMenu.WidthOffset, TextPanelVehicle.Background.Height + 200, 0, 255, 255, 255, 255);
            OnlylifeUI.StatisticPanelCount = OnlylifeUI.StatisticPanelCount + 1
        end
    end
end

---@type Panel
function OnlylifeUI.RenderPackEntreprise(Dictionary, Texture)
    local CurrentMenu = OnlylifeUI.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, 345, TextPanelVehicle.Background.Width + CurrentMenu.WidthOffset, TextPanelVehicle.Background.Height + 200, 0, 255, 255, 255, 255);
            OnlylifeUI.StatisticPanelCount = OnlylifeUI.StatisticPanelCount + 1
        end
    end
end

function OnlylifeUI.RenderPackIllegal(Dictionary, Texture)
    local CurrentMenu = OnlylifeUI.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, 285, TextPanelVehicle.Background.Width + CurrentMenu.WidthOffset, TextPanelVehicle.Background.Height + 200, 0, 255, 255, 255, 255);
            OnlylifeUI.StatisticPanelCount = OnlylifeUI.StatisticPanelCount + 1
        end
    end
end